// Supabase project credentials. The anon key is meant to be public (it only
// grants what Row Level Security on the database allows) — see supabase/schema.sql
// for the policies that actually protect the data.
//
// For local development: copy this file to config.js (gitignored) and fill
// in your project's values from Settings → API in the Supabase dashboard.
//
// For the deployed site: config.js is generated by .github/workflows/deploy.yml
// from the SUPABASE_URL / SUPABASE_ANON_KEY repository secrets — it's never
// committed, so the real values never live in git history.
export const SUPABASE_URL = "";
export const SUPABASE_ANON_KEY = "";
